# Generated by Django 5.1.6 on 2025-03-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', 'create_superuser'),
        ('jobs', 'search_triggers'),
    ]

    operations = [
    ]
