# Generated by Django 5.1.6 on 2025-03-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_merge_create_superuser_search_triggers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='status',
            new_name='is_active',
        ),
    ]
