# Generated by Django 5.1.6 on 2025-03-05 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', 'create_superuser'),
        ('jobs', '0002_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_company', to='jobs.company'),
        ),
    ]
