# Generated by Django 5.1.6 on 2025-03-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('authentication', 'create_superuser'),
    ]

    operations = [
    ]
