# Generated by Django 5.1.6 on 2025-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Applicant', 'Applicant'), ('Employer', 'Employer')], max_length=255, unique=True),
        ),
    ]
